# Generated by Django 4.1.1 on 2022-09-26 16:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='email')),
                ('contact', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format: 0241301463', regex='^(0)\\d{9}$')])),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('other_name', models.CharField(max_length=10, verbose_name='Other Names')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('admin', models.BooleanField(default=False, verbose_name='Admin')),
                ('superuser', models.BooleanField(default=False, verbose_name='Superuser')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='Registration Date')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Last Login')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'auth_user',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='staff_user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('category', models.CharField(choices=[('Manager', 'Manager'), ('Sales Person', 'Sales Person'), ('Finance', 'Finance'), ('Cooks', 'Cooks'), ('Staff', 'Staff')], default=('Staff', 'Staff'), max_length=50)),
                ('position', models.CharField(max_length=50, verbose_name='Staff Rank')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='user/profile_imgs', verbose_name='Image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
