# Generated by Django 4.1.1 on 2022-09-26 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import order.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('ref', models.CharField(default=order.models.cart_ref_generator, max_length=120, primary_key=True, serialize=False, unique=True)),
                ('price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('qty', models.PositiveSmallIntegerField(default=1)),
                ('ordered', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_menu', to='menu.menu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('invoice', models.CharField(auto_created=True, default=order.models.invoice_generator, editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_contact', models.CharField(blank=True, max_length=13, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('delivery_address', models.CharField(blank=True, max_length=250, null=True)),
                ('address_description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('served', models.BooleanField(default=False)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('e_cash', (('mtn', 'MTN'), ('voda', 'Vodafone'), ('bank', 'Bank Transfer')))], default='cash', max_length=50, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ManyToManyField(related_name='cart_ordered', to='order.cart')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_orders', to=settings.AUTH_USER_MODEL)),
                ('served_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='served_orders', to='account.staff')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_orders', to='account.staff')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
